name: 'brakeman sast scan'
on:
  workflow_dispatch:
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # latest brakeman wants ruby >= 3.0.0
      - run: gem install brakeman
      - run: brakeman --color -o /dev/stdout -o output.json -o output.html -o output.sarif --no-exit-on-warn --no-exit-on-error --no-pager
      - name: save artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: brakeman-report
          path: |
            output.json
            output.html
            output.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: output.sarif
          category: brakeman
